### ISSUE TITLE
Create import mapping for each new TolaActivity API form

### ISSUE THREAD

**Issue by glind** [mercycorps/tola#31]
After the new share data dropdown has been populated with the TolaActivity main forms create an import function similar to the merge function (reusing as much as possible) that allows the user to map there silo to the TolaAcitivty API fields.

Example: (use options to populate to fields for migrate or merge function)
https://tola-activity.mercycorps.org/api/proposals/

**Comment by mahmoodkhan** [comment]
This has been moved to the rest_api; it will be a pull not a push.
