### ISSUE TITLE
Ethiopia team can not connect to Ona accounts in Tola Data

### ISSUE THREAD

**Issue by glind** [mercycorps/tola#53]
Joash and ethiopia team are trying to connect the mcethiopia Ona account to tola data and keep getting a key error message from TD about the api token.

I have confirmed that an API has been generated.

**Comment by mahmoodkhan** [comment]
The only way I can duplicate this is by typing incorrect password. If I type in the correct username and password, it works just fine. I tested it on a new account I just created for ONA as well as the mcethiopia account. It works for both of them. I will add some logic to detect incorrect login and display a more user-friendly error message
