### ISSUE TITLE
tried to export merged dataset as excel

### ISSUE THREAD

**Issue by glind** [mercycorps/tola#67]
shemingway@iq.mercycorps.org .  We may need to flow up on this but it sounded like they were having trouble exporting a merged dataset to Excel.

**Comment by glind** [comment]
Can you get clarification on this and figure out if it's still an issue?  This is an Iraq issue so I don't want to assign dev time to it unless we know it's legit.

**Comment by andrewtpham** [comment]
Last time I checked it still wasn't working. this was a legit issue that when I
was in Erbil. I can take look again just to make sure then reassign.
A

On Thu, Dec 17, 2015 at 2:59 AM, Greg Lind <notifications@github.com> wrote:
Can you get clarification on this and figure out if it's still an issue? This is
an Iraq issue so I don't want to assign dev time to it unless we know it's
legit.

—
Reply to this email directly or view it on GitHub
[https://github.com/mercycorps/tola/issues/67#issuecomment-165226168] .[https://github.com/notifications/beacon/AEM_F1LXyrIconCRIxLUqgzYIVXE6NK5ks5pQbohgaJpZM4GavMY.gif]
