### ISSUE TITLE
erroe when entering new table

### ISSUE THREAD

**Issue by glind** [mercycorps/tola#73]
skouzi@lb.mercycorps.org when I was entering a new table on Tola Data after I submit the CSV file, I got the below attached error page.

**Comment by mahmoodkhan** [comment]
Where is the error? I don't see it.

**Comment by andrewtpham** [comment]
Hi Mahmood, the attachment is showing up in Tola Work. Can you check that, maybe the attachment didn't make it to github

**Comment by mahmoodkhan** [comment]
Can you send me the file that was attempted to upload?
