### ISSUE TITLE
Tola Data Help links should link to Tola.Work

### ISSUE THREAD

**Issue by glind** [mercycorps/tola#74]
ksandstrom@mercycorps.org The Help Links on Tola Data/Tables should link to Tola.Work
https://tola-data.mercycorps.org/faq --> http://tola.work/faq

https://tola-data.mercycorps.org/contact --> http://tola.work/contact

https://tola-data.mercycorps.org/documentation --> http://tola.work/documentation

**Comment by mahmoodkhan** [comment]
They already do.
